// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT IT DIRECTLY!
export default [  {
    "id": 6,
    "name": "Marie Curtis Park",
    "latitude": 43.58564323,
    "longitude": -79.54407233,
    "address": "2 Forty Second St",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 6,
    "name": "Marie Curtis Park",
    "latitude": 43.58564323,
    "longitude": -79.54407233,
    "address": "2 Forty Second St",
    "phone": " ",
    "category": "Wading Pool"
  },  {
    "id": 7,
    "name": "Broadlands Community Centre",
    "latitude": 43.745989,
    "longitude": -79.322827,
    "address": "19 Castlegrove Blvd",
    "phone": "416-395-7966",
    "category": "Outdoor Pool"
  },  {
    "id": 17,
    "name": "Annette Community Recreation Centre",
    "latitude": 43.661273,
    "longitude": -79.474259,
    "address": "333 Annette St",
    "phone": "416-392-0736",
    "category": "Indoor Pool"
  },  {
    "id": 24,
    "name": "Beaches Recreation Centre",
    "latitude": 43.673955,
    "longitude": -79.298821,
    "address": "6 Williamson Rd",
    "phone": "416-392-0740",
    "category": "Indoor Pool"
  },  {
    "id": 27,
    "name": "Bedford Park Community Centre",
    "latitude": 43.728173,
    "longitude": -79.399908,
    "address": "81 Ranleigh Ave",
    "phone": "416-392-0618",
    "category": "Indoor Pool"
  },  {
    "id": 31,
    "name": "Alexandra Park",
    "latitude": 43.651152,
    "longitude": -79.404958,
    "address": "275 Bathurst St",
    "phone": "416-392-7686",
    "category": "Outdoor Pool"
  },  {
    "id": 31,
    "name": "Alexandra Park",
    "latitude": 43.651152,
    "longitude": -79.404958,
    "address": "275 Bathurst St",
    "phone": "416-392-7686",
    "category": "Splash/Spray Pad"
  },  {
    "id": 36,
    "name": "Earl Beatty Community Centre",
    "latitude": 43.686461,
    "longitude": -79.321143,
    "address": "455 Glebeholme Blvd",
    "phone": "416-392-0752",
    "category": "Indoor Pool"
  },  {
    "id": 38,
    "name": "Marian Engel Park",
    "latitude": 43.67371745,
    "longitude": -79.42436498,
    "address": "285 Melita Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 39,
    "name": "Frankland Community Centre",
    "latitude": 43.677428,
    "longitude": -79.349662,
    "address": "816 Logan Ave",
    "phone": "416-392-0749",
    "category": "Indoor Pool"
  },  {
    "id": 42,
    "name": "Antibes Community Centre",
    "latitude": 43.781211,
    "longitude": -79.446795,
    "address": "140 Antibes Dr",
    "phone": "416-395-0096",
    "category": "Indoor Pool"
  },  {
    "id": 45,
    "name": "Harrison Pool",
    "latitude": 43.65108109,
    "longitude": -79.39079613,
    "address": "15 Stephanie St",
    "phone": "416-392-7984",
    "category": "Indoor Pool"
  },  {
    "id": 46,
    "name": "Geary Avenue Parkette",
    "latitude": 43.67090966,
    "longitude": -79.43092788,
    "address": "15 Geary Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 48,
    "name": "Hillcrest Community Centre",
    "latitude": 43.679051,
    "longitude": -79.415687,
    "address": "1339 Bathurst St",
    "phone": "416-392-0746",
    "category": "Indoor Pool"
  },  {
    "id": 49,
    "name": "Masaryk Park",
    "latitude": 43.64024836,
    "longitude": -79.4333265,
    "address": "212 Cowan Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 58,
    "name": "Jimmie Simpson Recreation Centre",
    "latitude": 43.660041,
    "longitude": -79.344948,
    "address": "870 Queen St",
    "phone": "416-392-0751",
    "category": "Indoor Pool"
  },  {
    "id": 60,
    "name": "Mccormick Park",
    "latitude": 43.647492,
    "longitude": -79.432833,
    "address": "66 Sheridan Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 63,
    "name": "John Innes Community Recreation Centre",
    "latitude": 43.65557,
    "longitude": -79.369955,
    "address": "150 Sherbourne St",
    "phone": "416-392-6779",
    "category": "Indoor Pool"
  },  {
    "id": 67,
    "name": "Jonathan Ashbridge Park",
    "latitude": 43.66464268,
    "longitude": -79.32013169,
    "address": "1515 Queen St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 70,
    "name": "Greenwood Park",
    "latitude": 43.66855,
    "longitude": -79.328748,
    "address": "150 Greenwood Ave",
    "phone": "416-392-7804",
    "category": "Outdoor Pool"
  },  {
    "id": 70,
    "name": "Greenwood Park",
    "latitude": 43.66855,
    "longitude": -79.328748,
    "address": "150 Greenwood Ave",
    "phone": "416-392-7804",
    "category": "Splash/Spray Pad"
  },  {
    "id": 71,
    "name": "Sir Casimir Gzowski Park",
    "latitude": 43.6349239,
    "longitude": -79.46631982,
    "address": "2001 Lake Shore Blvd",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 72,
    "name": "Fred Hamilton Playground",
    "latitude": 43.65290885,
    "longitude": -79.42043039,
    "address": "155 Roxton Rd",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 73,
    "name": "Art Eggleton Park",
    "latitude": 43.65889417,
    "longitude": -79.41835802,
    "address": "323 Harbord St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 75,
    "name": "Hideaway Park",
    "latitude": 43.66455493,
    "longitude": -79.338183,
    "address": "23 Audley Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 77,
    "name": "High Park",
    "latitude": 43.64654,
    "longitude": -79.463497,
    "address": "1873 Bloor St",
    "phone": "416-392-7807",
    "category": "Outdoor Pool"
  },  {
    "id": 77,
    "name": "High Park",
    "latitude": 43.64654,
    "longitude": -79.463497,
    "address": "1873 Bloor St",
    "phone": "416-392-7807",
    "category": "Splash/Spray Pad"
  },  {
    "id": 77,
    "name": "High Park",
    "latitude": 43.64654,
    "longitude": -79.463497,
    "address": "1873 Bloor St",
    "phone": "416-392-7807",
    "category": "Wading Pool"
  },  {
    "id": 78,
    "name": "June Rowlands Park",
    "latitude": 43.70063949,
    "longitude": -79.38872884,
    "address": "220 Davisville Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 79,
    "name": "Hillcrest Park",
    "latitude": 43.67592887,
    "longitude": -79.42472448,
    "address": "950 Davenport Rd",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 85,
    "name": "Main Square Community Centre",
    "latitude": 43.687164,
    "longitude": -79.29985,
    "address": "245 Main St",
    "phone": "416-392-1070",
    "category": "Indoor Pool"
  },  {
    "id": 86,
    "name": "Dovercourt Park",
    "latitude": 43.66515956,
    "longitude": -79.43373286,
    "address": "155 Bartlett Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 87,
    "name": "Dufferin Grove Park",
    "latitude": 43.65624245,
    "longitude": -79.43268597,
    "address": "875 Dufferin St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 100,
    "name": "Mary Mccormick Recreation Centre",
    "latitude": 43.647477,
    "longitude": -79.432802,
    "address": "66 Sheridan Ave",
    "phone": "416-392-0742",
    "category": "Indoor Pool"
  },  {
    "id": 107,
    "name": "Kew Gardens",
    "latitude": 43.667946,
    "longitude": -79.29778,
    "address": "2075 Queen St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 108,
    "name": "East Lynn Park",
    "latitude": 43.68415167,
    "longitude": -79.31557247,
    "address": "1949 Danforth Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 111,
    "name": "East Toronto Athletic Field",
    "latitude": 43.68524125,
    "longitude": -79.29935248,
    "address": "175 Main St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 117,
    "name": "Eglinton Park",
    "latitude": 43.70740121,
    "longitude": -79.40552685,
    "address": "200 Eglinton Ave",
    "phone": "416-392-6585",
    "category": "Wading Pool"
  },  {
    "id": 123,
    "name": "Leslie Grove Park",
    "latitude": 43.66310396,
    "longitude": -79.33375935,
    "address": "1158 Queen St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 125,
    "name": "Lithuania Park",
    "latitude": 43.65869299,
    "longitude": -79.46320025,
    "address": "155 Oakmount Rd",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 126,
    "name": "Margaret Fairley Park",
    "latitude": 43.66021508,
    "longitude": -79.40582689,
    "address": "100 Brunswick Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 127,
    "name": "Fairmount Park",
    "latitude": 43.67583716,
    "longitude": -79.31592609,
    "address": "1725 Gerrard St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 128,
    "name": "Little Norway Park",
    "latitude": 43.63422378,
    "longitude": -79.39868073,
    "address": "659 Queens Quay ",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 137,
    "name": "Baird Park",
    "latitude": 43.66232367,
    "longitude": -79.46279072,
    "address": "275 Keele St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 145,
    "name": "Monarch Park",
    "latitude": 43.678849,
    "longitude": -79.32627,
    "address": "115 Felstead Ave",
    "phone": "416-392-7831",
    "category": "Outdoor Pool"
  },  {
    "id": 145,
    "name": "Monarch Park",
    "latitude": 43.678849,
    "longitude": -79.32627,
    "address": "115 Felstead Ave",
    "phone": "416-392-7831",
    "category": "Wading Pool"
  },  {
    "id": 147,
    "name": "Carlton Park",
    "latitude": 43.66650714,
    "longitude": -79.45567501,
    "address": "20 Edith Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 148,
    "name": "Sackville Playground",
    "latitude": 43.65455135,
    "longitude": -79.36086779,
    "address": "420 King St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 149,
    "name": "Sherwood Park",
    "latitude": 43.71672437,
    "longitude": -79.3885194,
    "address": "190 Sherwood Ave",
    "phone": "416-392-0256",
    "category": "Wading Pool"
  },  {
    "id": 150,
    "name": "Randy Padmore Park",
    "latitude": 43.64975449,
    "longitude": -79.401045,
    "address": "47 Denison Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 155,
    "name": "Jimmie Simpson Park",
    "latitude": 43.660057,
    "longitude": -79.345227,
    "address": "870 Queen St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 157,
    "name": "Cassels Avenue Playground",
    "latitude": 43.68001384,
    "longitude": -79.30709619,
    "address": "69 Cassels Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 163,
    "name": "Barbara Hall Park",
    "latitude": 43.66662152,
    "longitude": -79.38071412,
    "address": "519 Church St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 167,
    "name": "Ramsden Park",
    "latitude": 43.67641,
    "longitude": -79.389569,
    "address": "1020 Yonge St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 168,
    "name": "Moorevale Park",
    "latitude": 43.69347618,
    "longitude": -79.38246474,
    "address": "175 Moore Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 170,
    "name": "Ravina Gardens",
    "latitude": 43.65992211,
    "longitude": -79.47365743,
    "address": "290 Clendenan Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 172,
    "name": "Spencer - Cowan Parkette",
    "latitude": 43.63631882,
    "longitude": -79.43090544,
    "address": "80 Spencer Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 174,
    "name": "Morse Street Playground",
    "latitude": 43.65678578,
    "longitude": -79.3402202,
    "address": "76 Morse St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 177,
    "name": "Moss Park",
    "latitude": 43.65501197,
    "longitude": -79.37127535,
    "address": "150 Sherbourne St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 181,
    "name": "Rennie Park",
    "latitude": 43.643058,
    "longitude": -79.472549,
    "address": "1 Rennie Ter",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 189,
    "name": "North Toronto Memorial Community Centre",
    "latitude": 43.706186,
    "longitude": -79.404249,
    "address": "200 Eglinton Ave",
    "phone": "416-392-6591",
    "category": "Indoor Pool"
  },  {
    "id": 189,
    "name": "North Toronto Memorial Community Centre",
    "latitude": 43.706186,
    "longitude": -79.404249,
    "address": "200 Eglinton Ave",
    "phone": "416-392-6591",
    "category": "Outdoor Pool"
  },  {
    "id": 190,
    "name": "Chelsea Avenue Playground",
    "latitude": 43.65732027,
    "longitude": -79.45594463,
    "address": "103 Chelsea Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 196,
    "name": "Christie Pits Park",
    "latitude": 43.664659,
    "longitude": -79.420842,
    "address": "750 Bloor St",
    "phone": " ",
    "category": "Wading Pool"
  },  {
    "id": 210,
    "name": "Rosedale Park",
    "latitude": 43.68272452,
    "longitude": -79.37912942,
    "address": "20 Scholfield Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 211,
    "name": "Close Avenue Parkette",
    "latitude": 43.63703505,
    "longitude": -79.43518297,
    "address": "116 Close Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 212,
    "name": "Stanley Park North - Toronto",
    "latitude": 43.64307555,
    "longitude": -79.41004117,
    "address": "890 King St",
    "phone": " ",
    "category": "Wading Pool"
  },  {
    "id": 214,
    "name": "Stephenson Park",
    "latitude": 43.68592807,
    "longitude": -79.30383372,
    "address": "61 Stephenson Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 220,
    "name": "Coleman Park",
    "latitude": 43.68934368,
    "longitude": -79.30001523,
    "address": "19 Coleman Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 221,
    "name": "Sumach - Shuter Parkette",
    "latitude": 43.65827159,
    "longitude": -79.35894797,
    "address": "485 Shuter St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 224,
    "name": "Northumberland Playground",
    "latitude": 43.6627298,
    "longitude": -79.42655574,
    "address": "770 Ossington Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 226,
    "name": "Columbus Parkette",
    "latitude": 43.65090331,
    "longitude": -79.44623037,
    "address": "1985 Dundas St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 228,
    "name": "Norwood Park",
    "latitude": 43.68230922,
    "longitude": -79.30336606,
    "address": "16 Norwood Rd",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 229,
    "name": "Lionel Conacher Park",
    "latitude": 43.68042937,
    "longitude": -79.39460733,
    "address": "80 Cottingham St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 234,
    "name": "Matty Eckler Recreation Centre",
    "latitude": 43.667886,
    "longitude": -79.339771,
    "address": "953 Gerrard St",
    "phone": "416-392-0750",
    "category": "Indoor Pool"
  },  {
    "id": 235,
    "name": "Runnymede Park",
    "latitude": 43.6682365,
    "longitude": -79.47874997,
    "address": "221 Ryding Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 236,
    "name": "Oakcrest Parkette",
    "latitude": 43.68347559,
    "longitude": -79.31166487,
    "address": "30 Oakcrest Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 241,
    "name": "Trinity Bellwoods Park",
    "latitude": 43.645515,
    "longitude": -79.413834,
    "address": "790 Queen St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 243,
    "name": "Parkdale Community Recreation Centre",
    "latitude": 43.643443,
    "longitude": -79.437478,
    "address": "75 Lansdowne Ave",
    "phone": "416-392-6696",
    "category": "Indoor Pool"
  },  {
    "id": 245,
    "name": "Oriole Park - Toronto",
    "latitude": 43.69719119,
    "longitude": -79.40043637,
    "address": "201 Oriole Pkwy",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 245,
    "name": "Oriole Park - Toronto",
    "latitude": 43.69719119,
    "longitude": -79.40043637,
    "address": "201 Oriole Pkwy",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 248,
    "name": "Osler Playground",
    "latitude": 43.64584224,
    "longitude": -79.42272385,
    "address": "123 Argyle St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 250,
    "name": "Vermont Square Park",
    "latitude": 43.67076974,
    "longitude": -79.41558656,
    "address": "819 Palmerston Ave",
    "phone": " ",
    "category": "Wading Pool"
  },  {
    "id": 257,
    "name": "Vine Avenue Playground",
    "latitude": 43.66693641,
    "longitude": -79.47069656,
    "address": "200 Vine Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 259,
    "name": "Wadsworth Park",
    "latitude": 43.67228522,
    "longitude": -79.45817036,
    "address": "120 Connolly St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 265,
    "name": "Wanless Park",
    "latitude": 43.72887803,
    "longitude": -79.3922559,
    "address": "250 Wanless Ave",
    "phone": "416-392-0256",
    "category": "Wading Pool"
  },  {
    "id": 267,
    "name": "S.h. Armstrong Community Centre",
    "latitude": 43.665945,
    "longitude": -79.322126,
    "address": "56 Woodfield Rd",
    "phone": "416-392-0734",
    "category": "Indoor Pool"
  },  {
    "id": 268,
    "name": "Joel Weeks Park",
    "latitude": 43.65948235,
    "longitude": -79.35298346,
    "address": "10 Thompson St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 270,
    "name": "Wellesley Park",
    "latitude": 43.66954666,
    "longitude": -79.36240104,
    "address": "500 Wellesley St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 272,
    "name": "St. Lawrence Community Recreation Centre",
    "latitude": 43.649807,
    "longitude": -79.36493,
    "address": "230 The Esplanade ",
    "phone": "416-392-1347",
    "category": "Indoor Pool"
  },  {
    "id": 274,
    "name": "Pelham Avenue Playground",
    "latitude": 43.6683341,
    "longitude": -79.45575836,
    "address": "20 Pelham Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 276,
    "name": "Topham Park",
    "latitude": 43.709918,
    "longitude": -79.306521,
    "address": "181 Westview Blvd",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 279,
    "name": "West Lodge Park",
    "latitude": 43.64604787,
    "longitude": -79.43818706,
    "address": "165 Lansdowne Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 282,
    "name": "Swansea Community Recreation Centre",
    "latitude": 43.643866,
    "longitude": -79.477022,
    "address": "15 Waller Ave",
    "phone": "416-392-6796",
    "category": "Indoor Pool"
  },  {
    "id": 284,
    "name": "Perth Square Park",
    "latitude": 43.66391378,
    "longitude": -79.45267615,
    "address": "350 Perth Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 287,
    "name": "Trinity Community Recreation Centre",
    "latitude": 43.646444,
    "longitude": -79.414973,
    "address": "155 Crawford St",
    "phone": "416-392-0743",
    "category": "Indoor Pool"
  },  {
    "id": 290,
    "name": "Beresford Park",
    "latitude": 43.65617682,
    "longitude": -79.4796644,
    "address": "400 Beresford Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 291,
    "name": "Healey Willan Park",
    "latitude": 43.6592219,
    "longitude": -79.41340576,
    "address": "504 Euclid Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 292,
    "name": "Phin Avenue Parkette",
    "latitude": 43.67786094,
    "longitude": -79.33651432,
    "address": "115 Condor Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 294,
    "name": "Wallace Emerson Community Centre",
    "latitude": 43.667441,
    "longitude": -79.439097,
    "address": "1260 Dufferin St",
    "phone": "416-392-0039",
    "category": "Indoor Pool"
  },  {
    "id": 296,
    "name": "Charles G. Williams Park",
    "latitude": 43.64748155,
    "longitude": -79.44347149,
    "address": "75 Wabash Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 300,
    "name": "Winchester Park",
    "latitude": 43.66561567,
    "longitude": -79.37199398,
    "address": "530 Ontario St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 306,
    "name": "Withrow Park And Clubhouse",
    "latitude": 43.674952,
    "longitude": -79.347131,
    "address": "725 Logan Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 307,
    "name": "Pottery Playground",
    "latitude": 43.69945324,
    "longitude": -79.37869543,
    "address": "601 Merton St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 308,
    "name": "Fairmount Park Community Centre",
    "latitude": 43.676593,
    "longitude": -79.314785,
    "address": "1757 Gerrard St",
    "phone": "416-392-7060",
    "category": "Indoor Pool"
  },  {
    "id": 312,
    "name": "Fenside Park",
    "latitude": 43.76484123,
    "longitude": -79.32742261,
    "address": "30 Slidell Cres",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 315,
    "name": "Primrose Avenue Parkette",
    "latitude": 43.67143615,
    "longitude": -79.44663737,
    "address": "120 Primrose Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 321,
    "name": "Leaside Outdoor Pool",
    "latitude": 43.70203158,
    "longitude": -79.35022813,
    "address": "5 Leaside Park Dr",
    "phone": "416-396-2846",
    "category": "Outdoor Pool"
  },  {
    "id": 327,
    "name": "Dieppe Park",
    "latitude": 43.691962,
    "longitude": -79.335642,
    "address": "455 Cosburn Ave",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 329,
    "name": "East York Community Centre",
    "latitude": 43.691732,
    "longitude": -79.349401,
    "address": "1081 Pape Ave",
    "phone": "416-396-2880",
    "category": "Indoor Pool"
  },  {
    "id": 335,
    "name": "Budapest Park",
    "latitude": 43.63680757,
    "longitude": -79.44956381,
    "address": "1575 Lake Shore Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 335,
    "name": "Budapest Park",
    "latitude": 43.63680757,
    "longitude": -79.44956381,
    "address": "1575 Lake Shore Blvd",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 337,
    "name": "Earl Bales Park",
    "latitude": 43.75259405,
    "longitude": -79.43131971,
    "address": "4169 Bathurst St",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 338,
    "name": "David Crombie Park",
    "latitude": 43.64853941,
    "longitude": -79.36810383,
    "address": "131 The Esplanade ",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 342,
    "name": "Northview Heights Secondary School",
    "latitude": 43.774503,
    "longitude": -79.446065,
    "address": "550 Finch Ave",
    "phone": "416-395-7965 ",
    "category": "Indoor Pool"
  },  {
    "id": 343,
    "name": "Riverdale Park East",
    "latitude": 43.66999498,
    "longitude": -79.35594026,
    "address": "550 Broadview Ave",
    "phone": " ",
    "category": "Outdoor Pool"
  },  {
    "id": 344,
    "name": "Riverdale Park West",
    "latitude": 43.66659338,
    "longitude": -79.3592231,
    "address": "375 Sumach St",
    "phone": " ",
    "category": "Wading Pool"
  },  {
    "id": 349,
    "name": "Spenvalley Park",
    "latitude": 43.74433903,
    "longitude": -79.50649183,
    "address": "130 Spenvalley Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 353,
    "name": "Kiwanis Outdoor Pool",
    "latitude": 43.69831218,
    "longitude": -79.31425482,
    "address": "375 Cedarvale Ave",
    "phone": "416-396-2847",
    "category": "Outdoor Pool"
  },  {
    "id": 357,
    "name": "Humber Community Pool",
    "latitude": 43.730849,
    "longitude": -79.608844,
    "address": "205 Humber College Blvd",
    "phone": "416-394-6050",
    "category": "Indoor Pool"
  },  {
    "id": 359,
    "name": "Albert Crosland Park",
    "latitude": 43.64072753,
    "longitude": -79.44029076,
    "address": "14 Fuller Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 378,
    "name": "Macgregor Playground",
    "latitude": 43.65310911,
    "longitude": -79.44230718,
    "address": "346 Lansdowne Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 384,
    "name": "Matty Eckler Playground",
    "latitude": 43.66794638,
    "longitude": -79.33854054,
    "address": "953 Gerrard St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 393,
    "name": "Wells Hill Park",
    "latitude": 43.68284052,
    "longitude": -79.4165921,
    "address": "145 Hilton Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 413,
    "name": "General Mercer School - Wading Pool",
    "latitude": 43.68032,
    "longitude": -79.46432,
    "address": "30 Turnberry Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 414,
    "name": "Alex Duff Memorial Pool",
    "latitude": 43.66461445,
    "longitude": -79.42099197,
    "address": "779 Crawford St",
    "phone": "416-392-0910",
    "category": "Outdoor Pool"
  },  {
    "id": 421,
    "name": "Stan Wadlow Park",
    "latitude": 43.69831218,
    "longitude": -79.31425482,
    "address": "888 Cosburn Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 423,
    "name": "R.v. Burgess Park",
    "latitude": 43.70374226,
    "longitude": -79.34394368,
    "address": "46 Thorncliffe Park Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 424,
    "name": "Howard Talbot Park",
    "latitude": 43.71021557,
    "longitude": -79.37374964,
    "address": "635 Eglinton Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 426,
    "name": "George Webster Park",
    "latitude": 43.70124076,
    "longitude": -79.30117396,
    "address": "30 Chapman Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 431,
    "name": "Woodbine Park",
    "latitude": 43.66387937,
    "longitude": -79.31310326,
    "address": "1695 Queen St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 433,
    "name": "Sunnyside Gus Ryder Outdoor Pool",
    "latitude": 43.63680116,
    "longitude": -79.4593602,
    "address": "1755 Lake Shore Blvd",
    "phone": "416-392-7915",
    "category": "Outdoor Pool"
  },  {
    "id": 437,
    "name": "Donald D. Summerville Olympic Pools",
    "latitude": 43.664903,
    "longitude": -79.304898,
    "address": "1867 Lake Shore Blvd",
    "phone": "416-392-7688",
    "category": "Outdoor Pool"
  },  {
    "id": 445,
    "name": "Woburn Avenue Playground",
    "latitude": 43.72743454,
    "longitude": -79.40597989,
    "address": "75 Woburn Ave",
    "phone": "416-392-6585",
    "category": "Wading Pool"
  },  {
    "id": 455,
    "name": "Massey Harris Park",
    "latitude": 43.64138465,
    "longitude": -79.41353321,
    "address": "945 King St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 456,
    "name": "Gamble Park",
    "latitude": 43.69105336,
    "longitude": -79.3472191,
    "address": "150 Gamble Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 461,
    "name": "Wychwood Barns Park",
    "latitude": 43.67948542,
    "longitude": -79.42390968,
    "address": "76 Wychwood Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 462,
    "name": "Joyce Trimmer Park",
    "latitude": 43.80555456,
    "longitude": -79.18975833,
    "address": "8450 Sheppard Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 474,
    "name": "Centennial Recreation Centre West",
    "latitude": 43.689863,
    "longitude": -79.478351,
    "address": "2694 Eglinton Ave",
    "phone": "416-394-2717",
    "category": "Indoor Pool"
  },  {
    "id": 480,
    "name": "Amesbury Sports Complex",
    "latitude": 43.706033,
    "longitude": -79.486735,
    "address": "155 Culford Rd",
    "phone": "416-395-0145",
    "category": "Outdoor Pool"
  },  {
    "id": 484,
    "name": "Amesbury Park",
    "latitude": 43.70613216,
    "longitude": -79.48361864,
    "address": "151 Culford Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 491,
    "name": "Ancaster Park",
    "latitude": 43.73337062,
    "longitude": -79.46570139,
    "address": "43 Ancaster Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 499,
    "name": "Cummer Park Community Centre",
    "latitude": 43.800139,
    "longitude": -79.3712,
    "address": "6000 Leslie St",
    "phone": "416-395-7803",
    "category": "Indoor Pool"
  },  {
    "id": 502,
    "name": "Fairbank Memorial Park",
    "latitude": 43.6915952,
    "longitude": -79.4478255,
    "address": "2213 Dufferin St",
    "phone": "416-394-2742",
    "category": "Outdoor Pool"
  },  {
    "id": 504,
    "name": "Smythe Park",
    "latitude": 43.67506516,
    "longitude": -79.49784608,
    "address": "61 Black Creek Blvd",
    "phone": "416-394-2741",
    "category": "Outdoor Pool"
  },  {
    "id": 504,
    "name": "Smythe Park",
    "latitude": 43.67506516,
    "longitude": -79.49784608,
    "address": "61 Black Creek Blvd",
    "phone": "416-394-2741",
    "category": "Splash/Spray Pad"
  },  {
    "id": 505,
    "name": "Balmoral Park",
    "latitude": 43.74480881,
    "longitude": -79.45008185,
    "address": "170 Faywood Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 506,
    "name": "Mcgregor Park Community Centre",
    "latitude": 43.747537,
    "longitude": -79.28008,
    "address": "2231 Lawrence Ave",
    "phone": "416-396-4023",
    "category": "Outdoor Pool"
  },  {
    "id": 507,
    "name": "Birchmount Community Centre",
    "latitude": 43.69531,
    "longitude": -79.261565,
    "address": "93 Birchmount Rd",
    "phone": "416-396-4311",
    "category": "Indoor Pool"
  },  {
    "id": 508,
    "name": "Weston Lions Park",
    "latitude": 43.69789026,
    "longitude": -79.51773465,
    "address": "2125 Lawrence Ave",
    "phone": "416-394-2743",
    "category": "Outdoor Pool"
  },  {
    "id": 508,
    "name": "Weston Lions Park",
    "latitude": 43.69789026,
    "longitude": -79.51773465,
    "address": "2125 Lawrence Ave",
    "phone": "416-394-2743",
    "category": "Splash/Spray Pad"
  },  {
    "id": 509,
    "name": "Joseph J. Piccininni Community Centre",
    "latitude": 43.675288,
    "longitude": -79.451574,
    "address": "1369 St Clair Ave",
    "phone": "416-392-0036",
    "category": "Indoor Pool"
  },  {
    "id": 510,
    "name": "Runnymede Collegiate Institute",
    "latitude": 43.663156,
    "longitude": -79.489852,
    "address": "569 Jane St",
    "phone": "416-392-0036",
    "category": "Indoor Pool"
  },  {
    "id": 514,
    "name": "Earlscourt Park",
    "latitude": 43.67356818,
    "longitude": -79.45170196,
    "address": "1200 Lansdowne Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 517,
    "name": "Bayview Village Park",
    "latitude": 43.77321524,
    "longitude": -79.38779361,
    "address": "2945 Bayview Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 518,
    "name": "Bellbury Park",
    "latitude": 43.78370457,
    "longitude": -79.36157183,
    "address": "55 Van Horne Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 522,
    "name": "Adams Park",
    "latitude": 43.79211331,
    "longitude": -79.14597949,
    "address": "2 Rozell Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 523,
    "name": "Agincourt Recreation Centre",
    "latitude": 43.788648,
    "longitude": -79.276013,
    "address": "31 Glen Watford Dr",
    "phone": "416-396-4037",
    "category": "Indoor Pool"
  },  {
    "id": 537,
    "name": "Centennial Recreation Centre - Scarborough",
    "latitude": 43.774614,
    "longitude": -79.236814,
    "address": "1967 Ellesmere Rd",
    "phone": "416-396-4057",
    "category": "Indoor Pool"
  },  {
    "id": 538,
    "name": "Berner Trail Park",
    "latitude": 43.80125582,
    "longitude": -79.22345563,
    "address": "45 Nahanni Ter",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 542,
    "name": "Leaside Memorial Gardens Swimming Pool - Indoor Pool",
    "latitude": 43.701891,
    "longitude": -79.360991,
    "address": "1073 Millwood Rd",
    "phone": "416-396-2822",
    "category": "Indoor Pool"
  },  {
    "id": 543,
    "name": "Thomson Memorial Park",
    "latitude": 43.7579199,
    "longitude": -79.25326761,
    "address": "1005 Brimley Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 547,
    "name": "Totts Tot Lot",
    "latitude": 43.71320387,
    "longitude": -79.23442889,
    "address": "1 Gradwell Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 554,
    "name": "Elm Park - North York",
    "latitude": 43.76983211,
    "longitude": -79.52541563,
    "address": "230 Gosford Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 556,
    "name": "Vradenberg Park",
    "latitude": 43.77479005,
    "longitude": -79.31039627,
    "address": "40 Vradenberg Dr",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 557,
    "name": "Blantyre Park",
    "latitude": 43.68300861,
    "longitude": -79.28089195,
    "address": "180 Fallingbrook Rd",
    "phone": "416-396-4126",
    "category": "Outdoor Pool"
  },  {
    "id": 559,
    "name": "Fennimore Park",
    "latitude": 43.7455929,
    "longitude": -79.52249135,
    "address": "78 Fennimore Cres",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 567,
    "name": "Douglas Snow Aquatic Centre",
    "latitude": 43.767245,
    "longitude": -79.41477,
    "address": "5100 Yonge St",
    "phone": "416-395-7585",
    "category": "Indoor Pool"
  },  {
    "id": 573,
    "name": "White Haven Park",
    "latitude": 43.78641328,
    "longitude": -79.24996628,
    "address": "63 Invergordon Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 575,
    "name": "Driftwood Community Recreation Centre",
    "latitude": 43.765384,
    "longitude": -79.518764,
    "address": "4401 Jane St",
    "phone": "416-395-7944",
    "category": "Outdoor Pool"
  },  {
    "id": 576,
    "name": "Corvette Park",
    "latitude": 43.72712277,
    "longitude": -79.25999445,
    "address": "40 Corvette Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 578,
    "name": "Bridlewood Park",
    "latitude": 43.78270993,
    "longitude": -79.31658642,
    "address": "445 Huntingwood Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 588,
    "name": "Flemington Park",
    "latitude": 43.72125375,
    "longitude": -79.44479078,
    "address": "2 Flemington Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 590,
    "name": "Seven Oaks Park",
    "latitude": 43.78819505,
    "longitude": -79.21078818,
    "address": "372 Military Trl",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 594,
    "name": "Elizabeth Simcoe Park",
    "latitude": 43.7393865,
    "longitude": -79.20495388,
    "address": "180 Sylvan Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 598,
    "name": "Shawn Blu Rose Park",
    "latitude": 43.81202146,
    "longitude": -79.20993048,
    "address": "30 Empringham Dr",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 605,
    "name": "Dunlop Park",
    "latitude": 43.71255815,
    "longitude": -79.26750027,
    "address": "19 Dunlop Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 622,
    "name": "John Tabor Park",
    "latitude": 43.80579132,
    "longitude": -79.20557479,
    "address": "240 John Tabor Trl",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 626,
    "name": "Terraview Park",
    "latitude": 43.76621785,
    "longitude": -79.31178477,
    "address": "1625 Pharmacy Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 629,
    "name": "Cedarvale Park",
    "latitude": 43.6922986,
    "longitude": -79.43075717,
    "address": "443 Arlington Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 632,
    "name": "Chalkfarm Park",
    "latitude": 43.72371066,
    "longitude": -79.5158252,
    "address": "2230 Jane St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 633,
    "name": "Heron Park Community Centre",
    "latitude": 43.768835,
    "longitude": -79.17578,
    "address": "292 Manse Rd",
    "phone": "416-396-4035",
    "category": "Outdoor Pool"
  },  {
    "id": 638,
    "name": "Glen Long Community Centre",
    "latitude": 43.708761,
    "longitude": -79.456113,
    "address": "35 Glen Long Ave",
    "phone": "416-395-7961",
    "category": "Outdoor Pool"
  },  {
    "id": 640,
    "name": "Glendora Park",
    "latitude": 43.76147328,
    "longitude": -79.4001222,
    "address": "201 Glendora Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 642,
    "name": "Gord And Irene Risk Community Centre",
    "latitude": 43.747443,
    "longitude": -79.56652,
    "address": "2650 Finch Ave",
    "phone": "416-395-0355",
    "category": "Outdoor Pool"
  },  {
    "id": 643,
    "name": "Goulding Community Centre",
    "latitude": 43.790626,
    "longitude": -79.422164,
    "address": "45 Goulding Ave",
    "phone": "416-395-0123",
    "category": "Outdoor Pool"
  },  {
    "id": 645,
    "name": "Gracedale Park",
    "latitude": 43.75188825,
    "longitude": -79.56236972,
    "address": "176 Gracedale Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 647,
    "name": "Grandravine Community Recreation Centre",
    "latitude": 43.751803,
    "longitude": -79.490574,
    "address": "23 Grandravine Dr",
    "phone": "416-395-6171",
    "category": "Outdoor Pool"
  },  {
    "id": 649,
    "name": "Graydon Hall Park",
    "latitude": 43.76281156,
    "longitude": -79.34268996,
    "address": "215 Graydon Hall Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 653,
    "name": "Harryetta Gardens",
    "latitude": 43.78158624,
    "longitude": -79.45167836,
    "address": "170 Torresdale Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 658,
    "name": "Heathrow Park",
    "latitude": 43.72442405,
    "longitude": -79.50811794,
    "address": "69 Heathrow Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 659,
    "name": "Hendon Park",
    "latitude": 43.78142074,
    "longitude": -79.42094828,
    "address": "50 Hendon Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 664,
    "name": "Irving W. Chapley Community Centre",
    "latitude": 43.761588,
    "longitude": -79.456089,
    "address": "205 Wilmington Ave",
    "phone": "416-395-0453",
    "category": "Outdoor Pool"
  },  {
    "id": 665,
    "name": "Irving W. Chapley Park",
    "latitude": 43.76172223,
    "longitude": -79.45541708,
    "address": "205 Wilmington Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 668,
    "name": "Glamorgan Park",
    "latitude": 43.77258975,
    "longitude": -79.28887711,
    "address": "50 Antrim Cres",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 674,
    "name": "Lanyard Park",
    "latitude": 43.74746162,
    "longitude": -79.54886783,
    "address": "138 Lanyard Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 675,
    "name": "Lawrence Heights Community Centre",
    "latitude": 43.71847,
    "longitude": -79.443102,
    "address": "5 Replin Rd",
    "phone": "416-395-6118",
    "category": "Outdoor Pool"
  },  {
    "id": 676,
    "name": "Highview Park",
    "latitude": 43.7026208,
    "longitude": -79.25814236,
    "address": "150 Highview Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 677,
    "name": "Horseley Hill Park",
    "latitude": 43.81072646,
    "longitude": -79.22973712,
    "address": "145 Horseley Hill Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 678,
    "name": "Ledbury Park",
    "latitude": 43.72678744,
    "longitude": -79.42596015,
    "address": "160 Ledbury St",
    "phone": "416-395-6688",
    "category": "Outdoor Pool"
  },  {
    "id": 689,
    "name": "Mcnicoll Park",
    "latitude": 43.79855513,
    "longitude": -79.35348461,
    "address": "215 Mcnicoll Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 690,
    "name": "Knob Hill Park",
    "latitude": 43.74388909,
    "longitude": -79.24846736,
    "address": "625 Brimley Rd",
    "phone": "416-396-4128",
    "category": "Outdoor Pool"
  },  {
    "id": 690,
    "name": "Knob Hill Park",
    "latitude": 43.74388909,
    "longitude": -79.24846736,
    "address": "625 Brimley Rd",
    "phone": "416-396-4128",
    "category": "Wading Pool"
  },  {
    "id": 693,
    "name": "Mitchell Field Community Centre",
    "latitude": 43.774539,
    "longitude": -79.408281,
    "address": "89 Church Ave",
    "phone": "416-395-0265",
    "category": "Outdoor Pool"
  },  {
    "id": 703,
    "name": "Northwood Community Centre",
    "latitude": 43.745563,
    "longitude": -79.500372,
    "address": "15 Clubhouse Crt",
    "phone": "416-395-7876",
    "category": "Outdoor Pool"
  },  {
    "id": 704,
    "name": "Maryvale Park",
    "latitude": 43.7530262,
    "longitude": -79.30672952,
    "address": "5 Trestleside Grv",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 714,
    "name": "Oriole Community Centre",
    "latitude": 43.78187,
    "longitude": -79.351131,
    "address": "2975 Don Mills Rd",
    "phone": "416-395-6005",
    "category": "Outdoor Pool"
  },  {
    "id": 718,
    "name": "Parkway Forest Park",
    "latitude": 43.77121473,
    "longitude": -79.34188434,
    "address": "80 Parkway Forest Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 719,
    "name": "Parma Park",
    "latitude": 43.717811,
    "longitude": -79.30234665,
    "address": "99 Parma Crt",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 723,
    "name": "Pelmo Park",
    "latitude": 43.71360366,
    "longitude": -79.51873203,
    "address": "171 Pellatt Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 732,
    "name": "Pleasantview Community Centre",
    "latitude": 43.786962,
    "longitude": -79.337102,
    "address": "545 Van Horne Ave",
    "phone": "416-395-6006",
    "category": "Outdoor Pool"
  },  {
    "id": 733,
    "name": "Prairie Drive Park",
    "latitude": 43.69705805,
    "longitude": -79.28432047,
    "address": "101 Pharmacy Ave Dr",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 739,
    "name": "Bob Hunter Park",
    "latitude": 43.8003992,
    "longitude": -79.16189641,
    "address": "205 Generation Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 741,
    "name": "Sandown Park",
    "latitude": 43.70994657,
    "longitude": -79.25355483,
    "address": "50 Natal Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 744,
    "name": "Roding Community Centre",
    "latitude": 43.729276,
    "longitude": -79.492601,
    "address": "600 Roding St",
    "phone": "416-395-7964",
    "category": "Outdoor Pool"
  },  {
    "id": 752,
    "name": "Sentinel Park",
    "latitude": 43.75514571,
    "longitude": -79.49874603,
    "address": "295 Sentinel Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 756,
    "name": "Shoreham Park",
    "latitude": 43.770792,
    "longitude": -79.519131,
    "address": "2 Shoreham Crt",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 760,
    "name": "Domenico Di Luca Community Recreation Centre",
    "latitude": 43.742429,
    "longitude": -79.515673,
    "address": "25 Stanley Rd",
    "phone": "416 395-6673",
    "category": "Outdoor Pool"
  },  {
    "id": 768,
    "name": "Halbert Park",
    "latitude": 43.72877269,
    "longitude": -79.23151286,
    "address": "24 Rockwood Dr",
    "phone": "416-396-4125",
    "category": "Outdoor Pool"
  },  {
    "id": 768,
    "name": "Halbert Park",
    "latitude": 43.72877269,
    "longitude": -79.23151286,
    "address": "24 Rockwood Dr",
    "phone": "416-396-4125",
    "category": "Wading Pool"
  },  {
    "id": 770,
    "name": "Van Horne Park",
    "latitude": 43.7865019,
    "longitude": -79.33941467,
    "address": "561 Van Horne Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 780,
    "name": "Oakdale Community Centre",
    "latitude": 43.747788,
    "longitude": -79.513149,
    "address": "350 Grandravine Dr",
    "phone": "416-395-0484",
    "category": "Outdoor Pool"
  },  {
    "id": 790,
    "name": "Maryvale Park Outdoor Pool",
    "latitude": 43.7530262,
    "longitude": -79.30672952,
    "address": "5 Trestleside Grv",
    "phone": "416-396-4127",
    "category": "Outdoor Pool"
  },  {
    "id": 792,
    "name": "Neilson Park - Scarborough",
    "latitude": 43.81348657,
    "longitude": -79.22435425,
    "address": "1555 Neilson Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 795,
    "name": "The Elms Pool And Community School",
    "latitude": 43.722739,
    "longitude": -79.551852,
    "address": "45 Golfdown Dr",
    "phone": "416-394-8722",
    "category": "Indoor Pool"
  },  {
    "id": 797,
    "name": "Norseman Community School And Pool",
    "latitude": 43.634316,
    "longitude": -79.516305,
    "address": "105 Norseman St",
    "phone": "416-394-8719",
    "category": "Indoor Pool"
  },  {
    "id": 798,
    "name": "Centennial Park - Etobicoke",
    "latitude": 43.656034,
    "longitude": -79.588882,
    "address": "256 Centennial Park Rd",
    "phone": " ",
    "category": "Wading Pool"
  },  {
    "id": 827,
    "name": "Birch Park",
    "latitude": 43.59168211,
    "longitude": -79.52829394,
    "address": "75 Arcadian Cir",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 836,
    "name": "Walter Saunders Memorial Park",
    "latitude": 43.6996848,
    "longitude": -79.44797492,
    "address": "440 Hopewell Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 844,
    "name": "Highfield Park",
    "latitude": 43.74431017,
    "longitude": -79.58939314,
    "address": "68 Stevenson Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 849,
    "name": "Martingrove Gardens Park",
    "latitude": 43.68911127,
    "longitude": -79.56353093,
    "address": "31 Lavington Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 854,
    "name": "Mimico Memorial Park",
    "latitude": 43.60975831,
    "longitude": -79.49386615,
    "address": "75 Hillside Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 858,
    "name": "Park Lawn Park",
    "latitude": 43.6370094,
    "longitude": -79.49481925,
    "address": "330 Park Lawn Rd",
    "phone": "416-394-8491",
    "category": "Outdoor Pool"
  },  {
    "id": 862,
    "name": "Rexdale Park",
    "latitude": 43.72367637,
    "longitude": -79.56552733,
    "address": "6 Drumheller Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 863,
    "name": "Rexlington Park",
    "latitude": 43.71650959,
    "longitude": -79.55954312,
    "address": "30 Bergamot Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 865,
    "name": "Willowdale Park",
    "latitude": 43.76602437,
    "longitude": -79.40786872,
    "address": "75 Hollywood Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 867,
    "name": "Rotary Peace Park",
    "latitude": 43.59389042,
    "longitude": -79.50591623,
    "address": "25 Eleventh St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 870,
    "name": "Summerlea Park",
    "latitude": 43.73107613,
    "longitude": -79.55081825,
    "address": "2 Arcot Blvd",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 871,
    "name": "Sunnydale Acres Park",
    "latitude": 43.72404271,
    "longitude": -79.57871854,
    "address": "50 Amoro Dr",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 881,
    "name": "West Scarborough Neighbourhood Centre",
    "latitude": 43.7005297,
    "longitude": -79.28435652,
    "address": "313 Pharmacy Ave",
    "phone": "416-755-9215",
    "category": "Indoor Pool"
  },  {
    "id": 887,
    "name": "Fairhaven Park Outdoor Pool",
    "latitude": 43.70177091,
    "longitude": -79.54513038,
    "address": "100 Golfwood Hts",
    "phone": "416-394-8486",
    "category": "Outdoor Pool"
  },  {
    "id": 888,
    "name": "Westmount Park Outdoor Pool",
    "latitude": 43.68724202,
    "longitude": -79.51897978,
    "address": "22 Arcade Dr",
    "phone": "416-394-8499",
    "category": "Outdoor Pool"
  },  {
    "id": 889,
    "name": "Richmond Gardens Pool",
    "latitude": 43.681851,
    "longitude": -79.545353,
    "address": "44 Strathdee Dr",
    "phone": "416-394-8493",
    "category": "Outdoor Pool"
  },  {
    "id": 891,
    "name": "Memorial Pool And Health Club",
    "latitude": 43.648428,
    "longitude": -79.519356,
    "address": "44 Montgomery Rd",
    "phone": "416-394-8731",
    "category": "Indoor Pool"
  },  {
    "id": 892,
    "name": "Etobicoke Olympium",
    "latitude": 43.650236,
    "longitude": -79.584349,
    "address": "590 Rathburn Rd",
    "phone": "416-394-8111",
    "category": "Indoor Pool"
  },  {
    "id": 893,
    "name": "Albion Pool And Health Club",
    "latitude": 43.739325,
    "longitude": -79.581284,
    "address": "1485 Albion Rd",
    "phone": "416-394-8676",
    "category": "Indoor Pool"
  },  {
    "id": 894,
    "name": "Gihon Spring Park Outdoor Pool",
    "latitude": 43.75447416,
    "longitude": -79.59482298,
    "address": "75 Gihon Spring Dr",
    "phone": "416-394-8488",
    "category": "Outdoor Pool"
  },  {
    "id": 895,
    "name": "Smithfield Park Outdoor Pool",
    "latitude": 43.74755159,
    "longitude": -79.59607509,
    "address": "175 Mount Olive Dr",
    "phone": "416-394-8495",
    "category": "Outdoor Pool"
  },  {
    "id": 896,
    "name": "Gus Ryder Pool And Health Club",
    "latitude": 43.601192,
    "longitude": -79.522114,
    "address": "1 Faustina Dr",
    "phone": "416-394-8726",
    "category": "Indoor Pool"
  },  {
    "id": 897,
    "name": "Alderwood Centre",
    "latitude": 43.601804,
    "longitude": -79.5477,
    "address": "2 Orianna Dr",
    "phone": "416-394-8738",
    "category": "Indoor Pool"
  },  {
    "id": 898,
    "name": "Flagstaff Park Outdoor Pool",
    "latitude": 43.72111996,
    "longitude": -79.59083238,
    "address": "42 Mercury Rd",
    "phone": "416-394-8487",
    "category": "Outdoor Pool"
  },  {
    "id": 899,
    "name": "Pine Point Park Outdoor Pool",
    "latitude": 43.71540123,
    "longitude": -79.54097075,
    "address": "15 Grierson Rd",
    "phone": "416-394-8492",
    "category": "Outdoor Pool"
  },  {
    "id": 900,
    "name": "Westgrove Park Outdoor Pool",
    "latitude": 43.68176605,
    "longitude": -79.56785509,
    "address": "15 Redgrave Dr",
    "phone": "416-394-8500",
    "category": "Outdoor Pool"
  },  {
    "id": 901,
    "name": "Eringate Park Outdoor Pool",
    "latitude": 43.66257189,
    "longitude": -79.58109333,
    "address": "121 Wellesworth Dr",
    "phone": "416-394-8485",
    "category": "Outdoor Pool"
  },  {
    "id": 902,
    "name": "Lambton - Kingsway Park Outdoor Pool",
    "latitude": 43.65752829,
    "longitude": -79.50800438,
    "address": "37 Marquis Ave",
    "phone": "416-394-8489",
    "category": "Outdoor Pool"
  },  {
    "id": 903,
    "name": "Wedgewood Park  Outdoor Pool",
    "latitude": 43.64441452,
    "longitude": -79.54772958,
    "address": "15 Swan Ave",
    "phone": "416-394-8496",
    "category": "Outdoor Pool"
  },  {
    "id": 904,
    "name": "West Deane Park Outdoor Pool",
    "latitude": 43.660649,
    "longitude": -79.561863,
    "address": "19 Sedgebrook Cres",
    "phone": "416-394-8497",
    "category": "Outdoor Pool"
  },  {
    "id": 905,
    "name": "West Mall Outdoor Pool",
    "latitude": 43.64249209,
    "longitude": -79.56689287,
    "address": "380 The West Mall ",
    "phone": "416-394-8498",
    "category": "Outdoor Pool"
  },  {
    "id": 906,
    "name": "Amos Waites Park Outdoor Pool",
    "latitude": 43.613291,
    "longitude": -79.48851345,
    "address": "2441 Lake Shore Blvd",
    "phone": "416-394-8484",
    "category": "Outdoor Pool"
  },  {
    "id": 907,
    "name": "Ourland Park Outdoor Pool",
    "latitude": 43.61549667,
    "longitude": -79.50889204,
    "address": "36 Ourland Ave",
    "phone": "416-394-8490",
    "category": "Outdoor Pool"
  },  {
    "id": 909,
    "name": "Rotary Peace Park Outdoor Pool",
    "latitude": 43.59389042,
    "longitude": -79.50591623,
    "address": "25 Eleventh St",
    "phone": "416-394-8494",
    "category": "Outdoor Pool"
  },  {
    "id": 915,
    "name": "Glen Park",
    "latitude": 43.65076816,
    "longitude": -79.55307571,
    "address": "44 Eastglen Cres",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 924,
    "name": "Prince Of Wales Park",
    "latitude": 43.5987857,
    "longitude": -79.4989802,
    "address": "1 Third St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 934,
    "name": "Trace Manes Park",
    "latitude": 43.70551558,
    "longitude": -79.36764861,
    "address": "110 Rumsey Rd",
    "phone": "416-396-2853",
    "category": "Wading Pool"
  },  {
    "id": 936,
    "name": "Indian Line Park",
    "latitude": 43.72491474,
    "longitude": -79.62265359,
    "address": "655 Humberwood Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 937,
    "name": "Oriole Park - North York",
    "latitude": 43.78143619,
    "longitude": -79.35120579,
    "address": "2955 Don Mills Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 939,
    "name": "Amos Waites Park",
    "latitude": 43.613291,
    "longitude": -79.48851345,
    "address": "2441 Lake Shore Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 959,
    "name": "Kingsview Park",
    "latitude": 43.69911321,
    "longitude": -79.55453744,
    "address": "46 Kingsview Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 962,
    "name": "Livingstone Park",
    "latitude": 43.69116835,
    "longitude": -79.35398315,
    "address": "21 Woodville Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 971,
    "name": "Greystone Park",
    "latitude": 43.72606867,
    "longitude": -79.25237482,
    "address": "845 Danforth Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 977,
    "name": "Lakeshore Village Park",
    "latitude": 43.60084377,
    "longitude": -79.51022875,
    "address": "45 Garnett Janes Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 981,
    "name": "Belmar Park",
    "latitude": 43.73197868,
    "longitude": -79.50981069,
    "address": "70 Monclova Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 998,
    "name": "North Humber Park",
    "latitude": 43.75736236,
    "longitude": -79.58785331,
    "address": "2851 Kipling Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1007,
    "name": "Fairhaven Park",
    "latitude": 43.70177091,
    "longitude": -79.54513038,
    "address": "100 Golfwood Hts",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 1021,
    "name": "Sunnylea Park",
    "latitude": 43.64150244,
    "longitude": -79.50182897,
    "address": "195 Prince Edward Dr",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 1032,
    "name": "Bell Manor Park",
    "latitude": 43.63747223,
    "longitude": -79.49257161,
    "address": "1 Bayside Lane",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1034,
    "name": "Michael Power Park",
    "latitude": 43.64522818,
    "longitude": -79.53123841,
    "address": "5055 Dundas St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1039,
    "name": "Eastview Park",
    "latitude": 43.76068121,
    "longitude": -79.19034906,
    "address": "33 Coronation Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1053,
    "name": "Campbell Avenue Playground",
    "latitude": 43.6635383,
    "longitude": -79.44849883,
    "address": "225 Campbell Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 1056,
    "name": "Dennis R. Timbrell Resource Centre",
    "latitude": 43.718018,
    "longitude": -79.331628,
    "address": "29 St Dennis Dr",
    "phone": "416-395-7972",
    "category": "Indoor Pool"
  },  {
    "id": 1057,
    "name": "Dentonia Park",
    "latitude": 43.693628,
    "longitude": -79.293737,
    "address": "80 Thyra Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1058,
    "name": "Don Russell Memorial Park",
    "latitude": 43.60141158,
    "longitude": -79.52150262,
    "address": "290 Birmingham St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 1068,
    "name": "Giovanni Caboto Rink, Pool And Tennis Courts",
    "latitude": 43.675704,
    "longitude": -79.45227,
    "address": "1367 St Clair Ave",
    "phone": "416-392-7662",
    "category": "Outdoor Pool"
  },  {
    "id": 1077,
    "name": "Kempton Howard Park",
    "latitude": 43.67615641,
    "longitude": -79.34035221,
    "address": "150 Blake St",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 1088,
    "name": "Milliken Park",
    "latitude": 43.82942526,
    "longitude": -79.27069386,
    "address": "5555 Steeles Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1093,
    "name": "O'connor Community Centre",
    "latitude": 43.717663,
    "longitude": -79.301931,
    "address": "1386 Victoria Park Ave",
    "phone": "416-395-7957",
    "category": "Outdoor Pool"
  },  {
    "id": 1094,
    "name": "Port Union Village Common Park",
    "latitude": 43.77569195,
    "longitude": -79.13530301,
    "address": "105 Bridgend St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1098,
    "name": "Scadding Court Community Centre",
    "latitude": 43.651665,
    "longitude": -79.404953,
    "address": "707 Dundas St",
    "phone": "416-392-0335",
    "category": "Indoor Pool"
  },  {
    "id": 1110,
    "name": "Albert Campbell Collegiate Institute",
    "latitude": 43.809265,
    "longitude": -79.272212,
    "address": "1550 Sandhurst Cir",
    "phone": "416-396-4009",
    "category": "Indoor Pool"
  },  {
    "id": 1143,
    "name": "Cedarbrae Collegiate Institute",
    "latitude": 43.756582,
    "longitude": -79.226156,
    "address": "550 Markham Rd",
    "phone": "416-396-4006",
    "category": "Indoor Pool"
  },  {
    "id": 1163,
    "name": "Cw Jefferys Collegiate Institute",
    "latitude": 43.758117,
    "longitude": -79.500353,
    "address": "340 Sentinel Rd",
    "phone": "416-395-7879",
    "category": "Indoor Pool"
  },  {
    "id": 1164,
    "name": "Da Morrison Middle School",
    "latitude": 43.694565,
    "longitude": -79.312094,
    "address": "271 Gledhill Ave",
    "phone": "416-392-6368",
    "category": "Indoor Pool"
  },  {
    "id": 1186,
    "name": "Emery Collegiate Institute",
    "latitude": 43.748271,
    "longitude": -79.539236,
    "address": "3395 Weston Rd",
    "phone": "416-395-7950",
    "category": "Indoor Pool"
  },  {
    "id": 1200,
    "name": "Georges Vanier Secondary School",
    "latitude": 43.783248,
    "longitude": -79.351126,
    "address": "3000 Don Mills Rd",
    "phone": "416-395-7975",
    "category": "Indoor Pool"
  },  {
    "id": 1205,
    "name": "Gordon A. Brown Middle School",
    "latitude": 43.706938,
    "longitude": -79.305835,
    "address": "2800 St Clair Ave",
    "phone": "416-392-6368",
    "category": "Indoor Pool"
  },  {
    "id": 1250,
    "name": "L'amoreaux Collegiate Institute",
    "latitude": 43.801504,
    "longitude": -79.31864,
    "address": "2501 Bridletowne Cir",
    "phone": "416-396-4005",
    "category": "Indoor Pool"
  },  {
    "id": 1255,
    "name": "Lester B. Pearson Collegiate Institute",
    "latitude": 43.803059,
    "longitude": -79.226017,
    "address": "150 Tapscott Rd",
    "phone": "416-396-4010",
    "category": "Indoor Pool"
  },  {
    "id": 1315,
    "name": "Sir Oliver Mowat Collegiate Institute",
    "latitude": 43.779385,
    "longitude": -79.142051,
    "address": "5400 Lawrence Ave",
    "phone": "416-396-4007",
    "category": "Indoor Pool"
  },  {
    "id": 1317,
    "name": "Sir Wilfrid Laurier Collegiate Institute",
    "latitude": 43.747571,
    "longitude": -79.197119,
    "address": "145 Guildwood Pkwy",
    "phone": "416-396-4011",
    "category": "Indoor Pool"
  },  {
    "id": 1371,
    "name": "Vaughan Road Academy",
    "latitude": 43.690589,
    "longitude": -79.436815,
    "address": "529 Vaughan Rd",
    "phone": "416-395-0242",
    "category": "Indoor Pool"
  },  {
    "id": 1373,
    "name": "Victoria Park Collegiate Institute",
    "latitude": 43.75568,
    "longitude": -79.321585,
    "address": "15 Wallingford Rd",
    "phone": "416-395-7842",
    "category": "Indoor Pool"
  },  {
    "id": 1381,
    "name": "West Hill Collegiate Institute",
    "latitude": 43.775738,
    "longitude": -79.190376,
    "address": "350 Morningside Ave",
    "phone": "416-396-4008",
    "category": "Indoor Pool"
  },  {
    "id": 1384,
    "name": "Weston Collegiate Institute",
    "latitude": 43.703739,
    "longitude": -79.509569,
    "address": "100 Pine St",
    "phone": "416-394-2739",
    "category": "Indoor Pool"
  },  {
    "id": 1387,
    "name": "Wexford Collegiate Institute",
    "latitude": 43.746001,
    "longitude": -79.306767,
    "address": "1176 Pharmacy Ave",
    "phone": "416-396-4016",
    "category": "Indoor Pool"
  },  {
    "id": 1399,
    "name": "York Mills Collegiate Institute",
    "latitude": 43.751097,
    "longitude": -79.37365,
    "address": "490 York Mills Rd",
    "phone": "416-395-7841",
    "category": "Indoor Pool"
  },  {
    "id": 1425,
    "name": "De Havilland 'mossie' Park",
    "latitude": 43.72730031,
    "longitude": -79.46802521,
    "address": "111 Anthony Rd",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1431,
    "name": "Grange Park",
    "latitude": 43.65249475,
    "longitude": -79.39242666,
    "address": "26 Grange Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1470,
    "name": "Morningside Park",
    "latitude": 43.77944401,
    "longitude": -79.19650665,
    "address": "390 Morningside Ave",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1480,
    "name": "Birunthan Park",
    "latitude": 43.82267836,
    "longitude": -79.22578127,
    "address": "31 Dragonfly Cres",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1495,
    "name": "Oates Park",
    "latitude": 43.7043477,
    "longitude": -79.27442439,
    "address": "10 Oates Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1496,
    "name": "Oakridge Park",
    "latitude": 43.69235133,
    "longitude": -79.27898691,
    "address": "3459 Danforth Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1748,
    "name": "Scarboro Crescent Park",
    "latitude": 43.70320362,
    "longitude": -79.24221971,
    "address": "61 Undercliff Dr",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1849,
    "name": "Lee Centre Park",
    "latitude": 43.78095821,
    "longitude": -79.24679934,
    "address": "112 Corporate Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1858,
    "name": "Loretto College - Wading Pool",
    "latitude": 43.67519,
    "longitude": -79.44444,
    "address": "151 Rosemount Ave",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 1860,
    "name": "Sherbourne Common",
    "latitude": 43.64441404,
    "longitude": -79.3649384,
    "address": "5 Lower Sherbourne St",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1865,
    "name": "Warden Hilltop Community Centre",
    "latitude": 43.714559,
    "longitude": -79.280944,
    "address": "25 Mendelssohn St",
    "phone": "416-392-7640",
    "category": "Splash/Spray Pad"
  },  {
    "id": 1882,
    "name": "Fairfield Park",
    "latitude": 43.63882629,
    "longitude": -79.51980116,
    "address": "90 Lothian Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2012,
    "name": "Regent Park Aquatic Centre",
    "latitude": 43.660828,
    "longitude": -79.360937,
    "address": "640 Dundas St",
    "phone": "416-338-2237",
    "category": "Indoor Pool"
  },  {
    "id": 2015,
    "name": "Florence Gell Park",
    "latitude": 43.66189098,
    "longitude": -79.49836343,
    "address": "85 Varsity Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2019,
    "name": "Birchcrest Park",
    "latitude": 43.79859491,
    "longitude": -79.32199055,
    "address": "89 Beverly Glen Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2020,
    "name": "Six Points Park",
    "latitude": 43.63957418,
    "longitude": -79.53613615,
    "address": "10 Viking Lane",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2021,
    "name": "Rita Cox Park",
    "latitude": 43.64007791,
    "longitude": -79.42577247,
    "address": "14 Machells Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2023,
    "name": "Aldwych Park",
    "latitude": 43.68490867,
    "longitude": -79.34141832,
    "address": "134 Aldwych Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2024,
    "name": "Toronto Island Park",
    "latitude": 43.62224628,
    "longitude": -79.38082461,
    "address": "9 Queens Quay ",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2025,
    "name": "Heron Park",
    "latitude": 43.76922739,
    "longitude": -79.17750525,
    "address": "292  Manse Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2027,
    "name": "Dufferin And King Park",
    "latitude": 43.63806906,
    "longitude": -79.4277259,
    "address": "256 Dufferin St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2030,
    "name": "Gledhill Park",
    "latitude": 43.69079458,
    "longitude": -79.31011395,
    "address": "125 Gledhill Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2031,
    "name": "Coronation Park - York",
    "latitude": 43.69093675,
    "longitude": -79.47996878,
    "address": "2700 Eglinton Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2032,
    "name": "Woburn Park - Scarborough",
    "latitude": 43.78142948,
    "longitude": -79.22785942,
    "address": "50 Dormington Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2034,
    "name": "Stephen Leacock Park",
    "latitude": 43.78716164,
    "longitude": -79.302686,
    "address": "2530 Birchmount Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2036,
    "name": "Mcgregor Park",
    "latitude": 43.74724675,
    "longitude": -79.28076178,
    "address": "2231 Lawrence Ave",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2037,
    "name": "Jack Goodlad Park",
    "latitude": 43.74239331,
    "longitude": -79.27011936,
    "address": "929 Kennedy Rd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2178,
    "name": "Brookbanks Park",
    "latitude": 43.75621201,
    "longitude": -79.33220715,
    "address": "75 Brookbanks Dr",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2251,
    "name": "Trudelle Park",
    "latitude": 43.74147478,
    "longitude": -79.24493732,
    "address": "36 Trudelle St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2261,
    "name": "Sugar Beach Park",
    "latitude": 43.64320851,
    "longitude": -79.36770125,
    "address": "11 Dockside Dr",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2663,
    "name": "Maple Claire Park",
    "latitude": 43.67259108,
    "longitude": -79.47308256,
    "address": "20 Viella St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2711,
    "name": "Avonshire Park",
    "latitude": 43.75792716,
    "longitude": -79.40464628,
    "address": "125 Harrison Garden Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2714,
    "name": "Tall Pines Park",
    "latitude": 43.79849589,
    "longitude": -79.15149387,
    "address": "64 Rylander Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2715,
    "name": "Joseph Bannon Park",
    "latitude": 43.73235892,
    "longitude": -79.5349725,
    "address": "65 Mary Chapman Blvd",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 2725,
    "name": "Toronto Island Park - Centre Island",
    "latitude": 43.61713041,
    "longitude": -79.37573912,
    "address": "9 Queens Quay ",
    "phone": "",
    "category": "Wading Pool"
  },  {
    "id": 2750,
    "name": "Stanley Park South - Toronto",
    "latitude": 43.64185386,
    "longitude": -79.40913303,
    "address": "700 Wellington St",
    "phone": "416-392-0703",
    "category": "Outdoor Pool"
  },  {
    "id": 2773,
    "name": "Toronto Pan Am Sports Centre",
    "latitude": 43.789444,
    "longitude": -79.193188,
    "address": "875 Morningside Ave",
    "phone": "416-283-5222",
    "category": "Indoor Pool"
  },  {
    "id": 2788,
    "name": "Regent Park",
    "latitude": 43.661011,
    "longitude": -79.362185,
    "address": "600 Dundas St",
    "phone": "",
    "category": "Splash/Spray Pad"
  },  {
    "id": 3499,
    "name": "Corktown Common",
    "latitude": 43.65397335,
    "longitude": -79.35261004,
    "address": "155 Bayview Ave",
    "phone": " ",
    "category": "Splash/Spray Pad"
  },  {
    "id": 3501,
    "name": "York Recreation Centre",
    "latitude": 43.68661771,
    "longitude": -79.48011899,
    "address": "115 Black Creek Dr",
    "phone": " 416-392-9675",
    "category": "Indoor Pool"
  },  {
    "id": 3559,
    "name": "Parkway Forest Outdoor Pool",
    "latitude": 43.772377,
    "longitude": -79.344396,
    "address": "59 Forest Manor Rd",
    "phone": "416-392-0945",
    "category": "Outdoor Pool"
  },  {
    "id": 3584,
    "name": "Diamond Jubilee Promenade",
    "latitude": 43.653351,
    "longitude": -79.355392,
    "address": "475 Front St",
    "phone": "",
    "category": "Splash/Spray Pad"
  }];